\input texinfo

@c %**start of header
@setfilename gnostic.info
@settitle Gnostic. User's guide
@c %**end of header

@copying
This is the user's guide for Gnostic 0.2

Copyright @copyright{} 2002, 2003, 2004 Juan M. Bello Rivas
@end copying

@titlepage
@title Gnostic 0.2
@subtitle User's guide
@subtitle Tutorial and reference manual.
@author Juan M. Bello Rivas

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Gnostic. User's guide

@insertcopying
@end ifnottex

@menu
* Introduction::	Introduction to Gnostic.
* Tutorial::		Step by step guide to Gnostic.
* Index::		Complete index.
@end menu

@node Introduction
@chapter Introduction

@cindex introduction

Gnostic is a versatile task launcher aimed at network and host security scanning.

@node Tutorial
@chapter Tutorial

@cindex tutorial

foo

@node Index
@unnumbered Index

@printindex cp

@bye
