\input texinfo

@c %**start of header
@setfilename gnostic.info
@settitle Gnostic
@c %**end of header

@include version.texi

@copying
This is the user's guide for @code{gnostic} @value{VERSION}

Copyright @copyright{} 2002, 2003, 2004 Juan M. Bello Rivas
@end copying

@titlepage
@title Gnostic
@subtitle A rule-based task execution system
@subtitle @code{gnostic} version @value{VERSION}
@author Juan M. Bello Rivas

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Gnostic

@insertcopying
@end ifnottex

@menu
* Introduction::	Introduction to @code{gnostic}.
* Invoking gnostic::	How to invoke @code{make} on the command line.
* Tutorial::		Step by step guide to @code{gnostic}.
* Index::		Complete index.
@end menu

@node Introduction
@chapter Introduction

@cindex introduction

The @code{gnostic} utility is a rule-based task execution system.  It evaluates
task dependencies and, if they are satisfied, executes the specified task.
This manual describes @code{gnostic}, which was implemented by Juan M. Bello
Rivas.

@node Invoking gnostic
@chapter Invoking gnostic
@cindex gnostic, invoking

foo

@node Tutorial
@chapter Tutorial

@cindex tutorial

foo

@node Index
@unnumbered Index

@printindex cp

@bye
